version: '2'
services:
  kafka-1:
    image: mytyan/kafka
    ports:
      - "3031:3031"
    networks:
      - network1
    volumes:
      - ./kafka1/server.properties:/home/kafka/kafka/config/server.properties

  kafka-2:
    image: mytyan/kafka
    ports:
      - "3032:3032"
    networks:
      - network1
    volumes:
      - ./kafka2/server.properties:/home/kafka/kafka/config/server.properties

  kafka-3:
    image: mytyan/kafka
    ports:
      - "3033:3033"
    networks:
      - network1
    volumes:
      - ./kafka3/server.properties:/home/kafka/kafka/config/server.properties

networks:
  network1:
    name: kafka-network
    external: true    